[package]
authors = ["zheng xin <moulo@126.com>"]
name = "pathfinding"
version = "0.0.1"
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/moulo1982/pathfinding.git"
description = """
一个寻路库，包含AStar和Recast，目前还在开发阶段
"""
[[example]]

[[test]]

[[bench]]

[dependencies]
