[package]
authors = ["zheng xin <moulo@126.com>"]
name = "pathfinding"
version = "0.0.1"
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/tokio-rs/mini-redis"

[dependencies]
